on:
  push:
    branches:
      - main
      - rc-*
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    name: release drafter
    steps:
      - name: Run release drafter
        uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          config-name: config/release-drafter.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
