name: ros-test

on:
  workflow_call:
    secrets:
      ssh_key:
        required: true
      known_hosts:
        required: true

jobs:
  ros:
    name: ros
    runs-on: ubuntu-latest
    container:
      image: ros:melodic
    steps:
      - name: Install ssh client
        run: |
          apt-get update
          apt-get install -y openssh-client
      - name: setup ssh key
        uses: shimataro/ssh-key-action@3c9b0fc6f2d223b8450b02a0445f526350fc73e0 # v2.3.1
        with:
          key: ${{ secrets.ssh_key }}
          known_hosts: ${{ secrets.known_hosts }}
      - name: Check out source repository
        uses: actions/checkout@v2
        with:
          path: ros/src/${{ github.event.repository.name }}
      - name: Download repositories managed wstool
        run: |
          wstool init .
          files=`find . -type f -regextype posix-egrep -regex "\./.+\.rosinstall"`
          while [ `echo ${files} | wc -w` -gt 0 ]
          do
            echo ${files} | xargs -n1 wstool merge -y -t .
            wstool up -t . -j4 -v
            rm ${files}
            files=`find . -type f -regextype posix-egrep -regex "\./.+\.rosinstall"`
          done
        shell: bash
        working-directory: ${{ github.workspace }}/ros/src
      - name: Install rosdep packages
        run: |
          rosdep update
          rosdep install -iry --from-paths . --rosdistro ${ROS_DISTRO}
        shell: bash
        working-directory: ${{ github.workspace }}/ros
      - name: Build ros packages
        run: |
          apt-get install -y python-catkin-tools
          source /opt/ros/${ROS_DISTRO}/setup.bash
          catkin init
          catkin config --extend /opt/ros/${ROS_DISTRO}
          catkin config --no-blacklist
          catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          catkin build
        shell: bash
        working-directory: ${{ github.workspace }}/ros
      - name: Run test
        run: |
          source devel/setup.bash
          catkin run_tests -i --no-deps --no-status ${{ github.event.repository.name }}
          catkin_test_results --verbose --all build || (trap - ERR && exit 1)
        shell: bash
        working-directory: ${{ github.workspace }}/ros
